id: P32FFE8E3
initial_creation_type: ocr
source_metadata:
  volumes:
    058b1998130945b9a38dc62c206ba063:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: འཕགས་མ་ལྷ་མོ་སྒྲོལ་མ་བསྒོམ་པའི་ཆོ་ག་རྒྱས་པ།
      total_pages: 1648
      volume_number: 40
